package kr.service.okr.domain.project.validator;

public enum ProjectValidatorType {
	VALIDATE_LEADER,
	VALIDATE_PROJECT_PERIOD,
	VALIDATE_KEYRESULT_COUNT,
	VALIDATE_PROJECT_INITIATIVE_DATE,
	VALIDATE_INITIATIVE_DONE,
	VALIDATE_INITIATIVE_IN_PROGRESS,
	VALIDATE_SELF_FEEDBACK,

}
