server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: okr-service

app:
  auth:
    tokenSecret: secretKey-test-okr-project-jwt-token
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
    refreshTokenRegenerationThreshold: 259200000


task-executor:
  core-pool-size: 10
  max-pool-size: 10
  queue-capacity: 10
