server:
  port: 8000

spring:
  application:
    name: okr-gateway-service
  cloud:
    gateway:
      routes:
        - id: okr-service
          uri: lb://OKR-SERVICE
          predicates:
            - Path=/api/**

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
          defaultZone: http://localhost:8761/eureka

