spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create #none
    properties:
      hibernate:
        show_sql: true
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true