

spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true