package kr.jay.okrver3.domain.project.validator;

public enum ProjectValidatorType {
	VALIDATE_LEADER,
	VALIDATE_PROJECT_PERIOD,
	VALIDATE_KEYRESULT_COUNT,
	VALIDATE_PROJECT_INITIATIVE_DATE,
	VALIDATE_INITIATIVE_DONE;

}
