server:
  port: 0

spring:
  application:
    name: okr-boot-project
  profiles:
    include:
      - infra-project-database
      - infra-jwt
      - api-project
      - infra-oauth
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


task-executor:
  core-pool-size: 20
  max-pool-size: 20
  queue-capacity: 20
